export { baseApi } from './baseApi';

export { useLazyGetMetricsQuery, useGetMetricsQuery } from './Metrics';
export { useGetAchievementLevelMutation } from './AchievementLevel';
export { useGetActivitiesRegistryMutation } from './ActivitiesRegistry';
export { useGetGeneralIndicatorsMutation } from './GeneralIndicators';
export { useGetNpParametersMutation } from './NpParameters';
export { useGetNpIndicatorsMutation } from './NpIndicators';
export { useGetIndicatorCountsMutation } from './IndicatorCounts';
export { useGetControlPointsMutation } from './ControlPoints';
export { useGetMapRegionsQuery, useGetSubjectsIndicatorTableQuery, useGetSubjectsResultTableQuery } from './MapRegions';
export { useGetFederalProjectNamesMutation } from './FederalProjectNames';
export { useGetFederalProjectAchievementLevelMutation } from './FederalProjects/AchievementLevel';
export { useGetFpParametersMutation } from './FederalProjects/FpParameters';
export { useGetDetailsFpIndicatorsMutation } from './FederalProjects/Indicators';
export { useGetControlPointByIdMutation } from './ControlPointById';
export { useGetUnacceptedBudgetObligationsMutation } from './UnacceptedBudgetObligations';
export { useGetProjectControlDataQuery } from './ProjectControlData';
export { useGetNpWithFpQuery } from './NpWithFp';
export { useLazyGetNationalProjectVersionQuery } from './NationalProjectVersion';
export { useGetReportExportStructureQuery } from './ReportExportStructure';
